### PR TITLE
add transit handlers

### PR DESCRIPTION
**Pull request by ianchow**
adds params on client and server for custom transit read & write handlers.

### CODE REVIEW

**Comment by mahinshaw** [comment]
Looks good.  I'm gonna test this out.

**Comment by mahinshaw** [comment]
@ianchow Can you rebase and make the PR into develop please?

**Comment by awkay** [comment]
@mahinshaw I switched the target branch in github. If that looks clean it can just be merged via the UI on github.

**Comment by mahinshaw** [comment]
@awkay Switching the target branch in github added a commit from Jeff. I'm guessing that is because @ianchow is working off of master. Which is why I was asking for the rebase.

**Comment by awkay** [comment]
Ah, yes, good catch.

**Comment by ianchow** [comment]
as a noob i've screwed up trying to rebase and am quite lost.

**Comment by mahinshaw** [comment]
@ianchow You should just be able to git reset HEAD~1 --soft which will give you your changes back. See them with git status. Then you can do git stash. Then git checkout develop. Then git stash pop. Then commit and push as usual.

**Comment by ianchow** [comment]
@mahinshaw thanks for help, tried that but looks like i'm in too deep a mess and am better off starting again and copying the 3 changed files over.

**Pull request closed without merging**
